name: Daily news update

on:
  schedule:
    - cron: '30 1 * * *'     # 07:00 AM IST
    - cron: '46 3 * * *'     # 09:16 AM IST
    - cron: '0 9 * * *'      # 02:30 PM IST
    - cron: '0 13 * * *'     # 06:30 PM IST
    - cron: '0 17 * * *'     # 10:30 PM IST
  push:
    branches:
      - main
  workflow_dispatch: # Enables manual runs from GitHub UI

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run daily script
        run: npm run update

      - name: Generate HTML
        run: npm run html

      - name: Commit generated index.html
        run: |
          git add index.html
          git commit -m "Automated update: $(date '+%Y-%m-%d %H:%M:%S')"
          git push origin main

      - name: Copy snapshot to history/
        run: |
          mkdir -p history
          cp data.json history/data-$(date '+%Y-%m-%d').json

      - name: Clean up history files older than 15 days
        run: |
          find history -name "data-*.json" | while read file; do
            file_date=$(basename "$file" | sed -E 's/data-([0-9]{4}-[0-9]{2}-[0-9]{2}).json/\1/')
            if [[ $(date -d "$file_date +15 days" +%s) -lt $(date +%s) ]]; then
              echo "Deleting $file (older than 15 days)"
              rm "$file"
            fi
          done

      - name: Commit snapshot
        run: |
          git add history/data-*.json
          git commit -m "Snapshot: $(date '+%Y-%m-%d %H:%M:%S')"
          git push origin main

      - name: Deploy to GitHub Pages 🌐
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          force_orphan: true

