name: Daily news update

on:
  schedule:
    - cron: '20 0 * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run daily script
        run: npm run update

      - name: Generate HTML
        run: npm run html

      - name: Commit generated index.html
        run: |
          git add index.html
          git commit -m "Automated update: $(date '+%Y-%m-%d %H:%M:%S')"
          git push origin main

      - name: Copy snapshot to history/
        run: |
          mkdir -p history
          cp data.json history/data-$(date '+%Y-%m-%d').json

      - name: Commit snapshot
        run: |
          git add history/data-*.json
          git commit -m "Snapshot: $(date '+%Y-%m-%d %H:%M:%S')"
          git push origin main

      - name: Deploy to GitHub Pages 🌐
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./

